language: node_js
node_js:
  - 10
  - 12
  - 14
  - 'lts/*'
  - 'node'
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.8
before_install:
  - sudo apt-get update
  - sudo apt purge python2.7-minimal
  - sudo apt-get install python3-pip python3-setuptools
  #- sudo apt-get install python3 python3-pip python3-setuptools
  - pip3 install --upgrade pip setuptools wheel
  - pip3 install git+https://github.com/forwardemail/authentication-headers.git
  - pip3 install pyspf
  - pip3 install dnspython==1.16.0
script:
  - npm run test-coverage
after_success:
  - npm run coverage
