language: node_js
node_js:
  - 10
  - 12
  - 14
  - 'lts/*'
  - 'node'
before_install:
  - sudo apt-get update
  - sudo apt purge python2.7-minimal
  - sudo apt-get install python3 python3-pip python3-setuptools
  - pip3 install --upgrade pip setuptools wheel
  - pip3 install authheaders dkimpy dnspython==1.16.0 pyspf
script:
  - npm run test-coverage
after_success:
  - npm run coverage
